#define MANEUVER_NONE 0
#define MANEUVER_PARKING_CROSS 1
#define MANEUVER_PARKING_PARALLEL 2
#define MANEUVER_PULL_OUT_LEFT 3
#define MANEUVER_STRAIGHT 4
#define MANEUVER_LEFT 5
#define MANEUVER_RIGHT 6
#define MANEUVER_SMALL_CURVE_LEFT 7
#define MANEUVER_SMALL_CURVE_RIGHT 8
#define MANEUVER_BIG_CURVE_LEFT 9
#define MANEUVER_BIG_CURVE_RIGHT 10
#define MANEUVER_STOP 11
#define MANEUVER_CONTINUOUS 12
#define MANEUVER_PULL_OUT_RIGHT 13
#define MANEUVER_STOP_FOR_PARKING 14

#define STEERING_STRAIGHT 91.5
#define STEERING_MAX_LEFT 75.0
#define STEERING_MAX_RIGHT 105.0
#define STEERING_MANEUVER_PULL_OUT_LEFT 60.0
#define STEERING_MANEUVER_PULL_OUT_RIGHT 120.0


